### ISSUE TITLE
Incompatible slf4j versions causes Datomic initialisation to fail

### ISSUE THREAD

**Issue by cursive-ghost** [onyx-platform/onyx-kafka#43]
I've been investigating an issue with @kennyjwilli which manifests itself when running a process from Cursive. The issue is that `onyx-kafka` contains a version of `slf4j-log4j` which is incompatible with the `log4j-api` in `onyx`. This causes Datomic to fail during initialisation.

Here's a sample `project.clj`:

```clojure
(defproject datomic-slf4j-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :repositories {"my.datomic.com" {:url   "https://my.datomic.com/repo"
                                   :creds :gpg}}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [com.datomic/datomic-pro "0.9.5561.50"]
                 [org.onyxplatform/onyx "0.11.0"]
                 [org.onyxplatform/onyx-kafka "0.11.0.0"]])
```

And a simple namespace:

```clojure
(ns datomic-slf4j-test.core)

(require 'datomic.api)
```

With this configuration, running `lein run -m datomic-slf4j-test.core` produces:

```
Caused by: java.lang.NoSuchMethodError: org.slf4j.helpers.Util.safeGetSystemProperty(Ljava/lang/String;)Ljava/lang/String;
	at org.slf4j.impl.VersionUtil.getJavaMajorVersion(VersionUtil.java:11)
	at org.slf4j.impl.Log4jMDCAdapter.<clinit>(Log4jMDCAdapter.java:37)
	at org.slf4j.impl.StaticMDCBinder.getMDCA(StaticMDCBinder.java:59)
	at org.slf4j.MDC.<clinit>(MDC.java:90)
	at datomic.slf4j__init.load(Unknown Source)
	at datomic.slf4j__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
```

If `onyx-kafka` is removed from the dependencies, this error is not produced.

Here's the deps tree:

```clojure
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.datomic/datomic-pro "0.9.5561.50"]
   [com.datomic/datomic-lucene-core "3.3.0"]
   [com.google.guava/guava "18.0"]
   [com.h2database/h2 "1.3.171"]
   [commons-codec "1.10"]
   [net.spy/spymemcached "2.11.4"]
   [org.apache.activemq/artemis-core-client "1.4.0" :exclusions [[org.jgroups/jgroups] [commons-logging]]]
     [io.netty/netty-all "4.0.39.Final"]
     [org.apache.activemq/artemis-commons "1.4.0"]
       [commons-beanutils "1.9.2"]
         [commons-collections "3.2.1"]
       [org.jboss.logging/jboss-logging "3.3.0.Final"]
     [org.apache.geronimo.specs/geronimo-json_1.0_spec "1.0-alpha-1"]
     [org.apache.johnzon/johnzon-core "0.9.4"]
   [org.apache.httpcomponents/httpclient "4.5.2" :exclusions [[commons-logging]]]
     [org.apache.httpcomponents/httpcore "4.4.4"]
   [org.apache.tomcat/tomcat-jdbc "7.0.27" :exclusions [[commons-logging]]]
     [org.apache.tomcat/tomcat-juli "7.0.27"]
   [org.clojure/tools.cli "0.3.5" :exclusions [[org.clojure/clojure]]]
   [org.codehaus.janino/commons-compiler-jdk "2.6.1"]
     [org.codehaus.janino/commons-compiler "2.6.1"]
   [org.fressian/fressian "0.6.5"]
   [org.slf4j/jcl-over-slf4j "1.7.7"]
   [org.slf4j/jul-to-slf4j "1.7.7"]
   [org.slf4j/log4j-over-slf4j "1.7.7" :scope "runtime"]
   [org.slf4j/slf4j-nop "1.7.7"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [org.onyxplatform/onyx-kafka "0.11.0.0"]
   [cheshire "5.7.0"]
     [com.fasterxml.jackson.core/jackson-core "2.8.6"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.8.6"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.8.6"]
     [tigris "0.1.1"]
   [org.apache.kafka/kafka-clients "0.11.0.0"]
     [org.xerial.snappy/snappy-java "1.1.2.6"]
   [org.apache.kafka/kafka_2.11 "0.11.0.0"]
     [com.101tec/zkclient "0.10" :exclusions [[*/mail] [*/jline] [*/netty] [*/jms] [*/javax] [*/jmxri] [*/jmxtools]]]
     [com.yammer.metrics/metrics-core "2.2.0" :exclusions [[*/mail] [*/jline] [*/netty] [*/jms] [*/javax] [*/jmxri] [*/jmxtools]]]
     [net.sf.jopt-simple/jopt-simple "5.0.3" :exclusions [[*/mail] [*/jline] [*/netty] [*/jms] [*/javax] [*/jmxri] [*/jmxtools]]]
     [org.scala-lang.modules/scala-parser-combinators_2.11 "1.0.4" :exclusions [[*/mail] [*/jline] [*/netty] [*/jms] [*/javax] [*/jmxri] [*/jmxtools]]]
     [org.scala-lang/scala-library "2.11.11" :exclusions [[*/mail] [*/jline] [*/netty] [*/jms] [*/javax] [*/jmxri] [*/jmxtools]]]
     [org.slf4j/slf4j-log4j12 "1.7.25" :exclusions [[*/mail] [*/jline] [*/netty] [*/jms] [*/javax] [*/jmxri] [*/jmxtools]]]
 [org.onyxplatform/onyx "0.11.0"]
   [clj-fuzzy "0.3.1" :exclusions [[org.clojure/clojurescript]]]
   [clj-tuple "0.2.2"]
   [com.amazonaws/aws-java-sdk-s3 "1.11.190"]
     [com.amazonaws/aws-java-sdk-core "1.11.190"]
       [com.fasterxml.jackson.core/jackson-databind "2.6.7.1"]
         [com.fasterxml.jackson.core/jackson-annotations "2.6.0"]
       [commons-logging "1.1.3"]
       [joda-time "2.8.1"]
       [software.amazon.ion/ion-java "1.0.2"]
     [com.amazonaws/aws-java-sdk-kms "1.11.190"]
     [com.amazonaws/jmespath-java "1.11.190"]
   [com.stuartsierra/component "0.3.2"]
   [com.stuartsierra/dependency "0.2.0"]
   [com.taoensso/nippy "2.13.0"]
     [net.jpountz.lz4/lz4 "1.3"]
     [org.clojure/tools.reader "0.10.0"]
     [org.iq80.snappy/snappy "0.4"]
     [org.tukaani/xz "1.6"]
   [com.taoensso/timbre "4.8.0"]
     [com.taoensso/encore "2.88.0"]
       [com.taoensso/truss "1.3.6"]
     [io.aviso/pretty "0.1.33"]
   [io.aeron/aeron-all "1.4.1"]
   [io.replikativ/hasch "0.3.3" :exclusions [[org.clojure/clojurescript] [com.cognitect/transit-clj] [com.cognitect/transit-cljs] [org.clojure/data.fressian] [com.cemerick/austin]]]
     [io.replikativ/incognito "0.2.0"]
   [metrics-clojure "2.9.0"]
     [io.dropwizard.metrics/metrics-core "3.1.2"]
   [net.cgrand/xforms "0.9.3"]
     [net.cgrand/macrovich "0.2.0"]
     [org.clojure/clojurescript "1.9.293"]
       [com.google.javascript/closure-compiler-unshaded "v20160911"]
         [com.google.code.findbugs/jsr305 "1.3.9"]
         [com.google.code.gson/gson "2.2.4"]
         [com.google.javascript/closure-compiler-externs "v20160911"]
         [com.google.jsinterop/jsinterop-annotations "1.0.0"]
         [com.google.protobuf/protobuf-java "2.5.0"]
       [org.clojure/data.json "0.2.6"]
       [org.clojure/google-closure-library "0.0-20160609-f42b4a24"]
         [org.clojure/google-closure-library-third-party "0.0-20160609-f42b4a24"]
       [org.mozilla/rhino "1.7R5"]
   [org.apache.curator/curator-framework "2.9.1"]
     [org.apache.curator/curator-client "2.9.1"]
   [org.apache.curator/curator-test "2.9.1"]
     [org.apache.commons/commons-math "2.2"]
     [org.javassist/javassist "3.18.1-GA"]
   [org.apache.zookeeper/zookeeper "3.4.10" :exclusions [[org.slf4j/slf4j-log4j12]]]
     [io.netty/netty "3.10.5.Final"]
     [jline "0.9.94" :exclusions [[*]]]
     [log4j "1.2.16" :exclusions [[*]]]
   [org.btrplace/scheduler-api "0.46"]
     [net.sf.trove4j/trove4j "3.0.3"]
   [org.btrplace/scheduler-choco "0.46"]
     [it.unimi.dsi/fastutil "7.0.12"]
     [org.choco-solver/choco-solver "3.3.3"]
       [args4j "2.32"]
       [com.github.cp-profiler/cpprof-java "1.1.0"]
         [org.zeromq/jeromq "0.3.4"]
       [dk.brics.automaton/automaton "1.11-8"]
       [org.javabits.jgrapht/jgrapht-core "0.9.3"]
   [org.clojure/core.async "0.3.443"]
     [org.clojure/tools.analyzer.jvm "0.7.0"]
       [org.clojure/core.memoize "0.5.9"]
         [org.clojure/core.cache "0.6.5"]
           [org.clojure/data.priority-map "0.0.7"]
       [org.clojure/tools.analyzer "0.6.9"]
       [org.ow2.asm/asm-all "4.2"]
   [org.deephacks.lmdbjni/lmdbjni-linux64 "0.4.6"]
   [org.deephacks.lmdbjni/lmdbjni-osx64 "0.4.6"]
   [org.deephacks.lmdbjni/lmdbjni-win64 "0.4.6"]
   [org.deephacks.lmdbjni/lmdbjni "0.4.6"]
   [org.slf4j/slf4j-api "1.7.12"]
   [prismatic/schema "1.1.6"]
```

The conflict is between `[org.slf4j/slf4j-api "1.7.12"]` and `[org.slf4j/slf4j-log4j12 "1.7.25" :exclusions ...]`. The [slf4j doc](https://www.slf4j.org/manual.html#compatibility) states: 

> Mixing different versions of slf4j-api.jar and SLF4J binding can cause problems. For example, if you are using slf4j-api-1.8.0-alpha2.jar, then you should also use slf4j-simple-1.8.0-alpha2.jar, using slf4j-simple-1.5.5.jar will not work.

> At initialization time, if SLF4J suspects that there may be an slf4j-api vs. binding version mismatch problem, it will emit a warning about the suspected mismatch.

**Comment by MichaelDrogalis** [comment]
Thanks for running this down! We'll try to get it looked at this week.

**Comment by MichaelDrogalis** [comment]
Fixed in master.
